version: '3.3'

services:  
  php72:
    build:
      context: .
      dockerfile: Dockerfile-php72
    ports:
      - "8085:80"
    restart: always
    volumes:
      - ${WWW_FOLDER}:/var/www/html
    networks: 
      - srv-dev-network

  php81:
    build:
      context: .
      dockerfile: Dockerfile-php81
    ports:
      - "8086:80"
    restart: always
    volumes:
      - ${WWW_FOLDER}:/var/www/html
    networks: 
      - srv-dev-network

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./mysql/data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # mysql:
  #   image: mysql:5.7
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: database_name
  #     MYSQL_ROOT_PASSWORD: 123qwe
  #     MYSQL_USER: someuser
  #     MYSQL_PASSWORD: 123qwe
  #   volumes:
  #     - ./mysql/data:/var/lib/mysql

  # phpmyadmin:
  #   image: phpmyadmin
  #   restart: always
  #   ports:
  #     - 8090:80
  #   environment:
  #     # - PMA_ARBITRARY=1
  #     - PMA_HOST=db
  #   depends_on:
  #     - db
  #   networks: 
  #     - srv-dev-network

networks:
  srv-dev-network:
    driver: bridge
